# Generated by Django 5.2 on 2026-08-01 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications', '0002_broadcastmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('all', 'All Users'), ('single', 'Single Specific User'), ('group', 'User Group (Role)')], default='all', help_text='Who should receive this email?', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Body content of the email.')),
                ('recipients_count', models.PositiveIntegerField(default=0, help_text='Total number of users who were sent this email.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, help_text="Required if 'User Group (Role)' is selected.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('recipient_user', models.ForeignKey(blank=True, help_text="Required if 'Single Specific User' is selected.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_broadcast_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Email',
                'verbose_name_plural': 'Broadcast Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BroadcastMessage',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'In-App Notification', 'verbose_name_plural': 'In-App Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System Notification'), ('order', 'Order Delivery / Update'), ('referral', 'Referral Commission'), ('promotion', 'Promotional Offer')], default='system', max_length=50),
        ),
    ]
