# Generated by Django 5.2 on 2026-07-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='crypto_network',
            field=models.CharField(blank=True, default='USDT (TRC20)', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_withdrawal_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('crypto', 'Crypto (USDT)')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='crypto_network',
            field=models.CharField(blank=True, default='USDT (TRC20)', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('crypto', 'Crypto (USDT)')], default='bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
