# Generated by Django 5.2 on 2026-08-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_account_name_profile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('success', 'Successful'), ('pending', 'Pending'), ('failed', 'Failed')], db_index=True, default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount_ngn',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit / Wallet Top-Up'), ('purchase', 'Tool Purchase'), ('withdrawal', 'Withdrawal'), ('referral_credit', 'Referral Commission')], max_length=20),
        ),
    ]
