# Generated by Django 5.2 on 2026-07-18 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_type', models.CharField(choices=[('akunding', 'Akunding'), ('shopbot', 'Shop Bot'), ('canboso', 'Canboso')], max_length=20)),
                ('base_url', models.URLField(blank=True, help_text='Optional, depending on vendor')),
                ('api_key', models.CharField(blank=True, help_text='Keep this secure', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook verification', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_product_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Vendor price in USD', max_digits=10, null=True)),
                ('stock', models.CharField(blank=True, help_text='e.g. 45 or unlimited', max_length=50)),
                ('is_manual', models.BooleanField(default=False, help_text='Does this product require manual delivery by the vendor?')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw JSON product data from vendor API', null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('vendor', 'vendor_product_id')},
            },
        ),
    ]
