# Generated by Django 5.2 on 2026-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_delivery_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_details',
            field=models.TextField(blank=True, help_text='Credentials/access info delivered to user after payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack payment reference for this order', max_length=200),
        ),
    ]
