# Generated by Django 5.2 on 2026-07-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_access_details_order_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Refunded'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Note from admin on rejection or approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
