# Generated by Django 5.2 on 2026-07-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_duration_days_orderitem_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='plan',
        ),
    ]
