# Generated by Django 5.2 on 2026-08-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_plan'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAPIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('vendor_order_id', models.CharField(blank=True, default='', max_length=200)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_requests', to='orders.order')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
                ('vendor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendorproduct')),
            ],
            options={
                'verbose_name': 'Vendor API Request',
                'verbose_name_plural': 'Vendor API Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
