# Generated by Django 5.2 on 2026-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderapirequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('wallet', 'Wallet Balance'), ('crypto', 'Crypto USDT'), ('manual', 'Manual')], max_length=50),
        ),
    ]
