# Generated by Django 5.2 on 2026-08-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_paymenttransaction_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_order_id',
            field=models.CharField(blank=True, help_text='Third-party vendor API order reference for admin reconciliation', max_length=255, null=True, verbose_name='Vendor Order ID'),
        ),
    ]
