# Generated by Django 5.2.6 on 2026-08-28 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_wallettransaction_transaction_type_apikey_and_more'),
        ('orders', '0009_order_claim_token_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='e.g. CM, GH, KE, NG, UG, TZ, ALL', max_length=5)),
                ('country_name', models.CharField(help_text='e.g. Cameroon, Ghana, Kenya, Nigeria, Uganda/Tanzania', max_length=100)),
                ('currency_code', models.CharField(help_text='e.g. XAF, GHS, KES, NGN, UGX, TZS', max_length=10)),
                ('payment_method_name', models.CharField(help_text='e.g. MTN MoMo, Telecel, Mpesa, Providus Bank', max_length=100)),
                ('account_number', models.CharField(help_text='Phone number or Bank account number', max_length=100)),
                ('account_name', models.CharField(help_text='Account holder name', max_length=150)),
                ('additional_instructions', models.TextField(blank=True, help_text='Specific instructions for this payment option')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manual Bank Account',
                'verbose_name_plural': 'Manual Bank Accounts',
                'ordering': ['display_order', 'country_name'],
            },
        ),
        migrations.CreateModel(
            name='ManualPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_channel_used', models.CharField(help_text='e.g. MTN MoMo, Telecel, Providus Bank, Mpesa', max_length=100)),
                ('sender_name_or_txid', models.CharField(help_text='Sender name or Transaction ID', max_length=200)),
                ('proof_file', models.FileField(help_text='Uploaded payment screenshot or PDF receipt', upload_to='manual_proofs/')),
                ('amount_local', models.DecimalField(decimal_places=2, help_text='Amount in user local currency', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('amount_ngn', models.DecimalField(decimal_places=2, help_text='Converted base NGN amount', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Reason for rejection or admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_proofs', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_proofs', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_proofs', to='accounts.wallettransaction')),
            ],
            options={
                'verbose_name': 'Manual Payment Proof',
                'verbose_name_plural': 'Manual Payment Proofs',
                'ordering': ['-created_at'],
            },
        ),
    ]
