# Generated by Django 5.2.6 on 2026-08-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_manualbankaccount_manualpaymentproof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualbankaccount',
            options={'ordering': ['display_order', 'payment_method_name'], 'verbose_name': 'Manual Bank Account', 'verbose_name_plural': 'Manual Bank Accounts'},
        ),
        migrations.AddField(
            model_name='manualbankaccount',
            name='supported_regions',
            field=models.CharField(blank=True, default='All Regions / Africa', help_text='e.g. Nigeria & Africa, Cameroon (XAF), Ghana (GHS), Kenya (KES)', max_length=150),
        ),
        migrations.AlterField(
            model_name='manualbankaccount',
            name='account_number',
            field=models.CharField(help_text='Bank account number or MoMo phone number', max_length=100),
        ),
        migrations.AlterField(
            model_name='manualbankaccount',
            name='additional_instructions',
            field=models.TextField(blank=True, help_text='Specific transfer notes (e.g. Include TxID & sender name)'),
        ),
        migrations.AlterField(
            model_name='manualbankaccount',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manualbankaccount',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manualbankaccount',
            name='currency_code',
            field=models.CharField(blank=True, default='ALL', help_text='e.g. XAF, GHS, KES, NGN, UGX, TZS or ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='manualbankaccount',
            name='payment_method_name',
            field=models.CharField(help_text='e.g. UBA Bank, MTN MoMo, Telecel, Mpesa, Providus Bank', max_length=100, verbose_name='Bank / Payment Provider Name'),
        ),
    ]
