# Generated by Django 5.2 on 2026-08-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('user_signup', 'User Registration'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_deleted', 'User Deleted'), ('order_created', 'Order Created'), ('order_paid', 'Order Paid'), ('order_failed', 'Order Failed'), ('order_fulfilled', 'Order Fulfilled'), ('payment_sent', 'Payment Initialized'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('wallet_topup', 'Wallet Top-Up'), ('wallet_purchase', 'Wallet Purchase'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('refund_rejected', 'Refund Rejected'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('vendor_sync', 'Vendor Product Sync'), ('vendor_balance', 'Vendor Balance Check'), ('admin_action', 'Admin Action'), ('system', 'System Event')], db_index=True, default='system', max_length=30),
        ),
    ]
