# Generated by Django 5.2 on 2026-07-14 02:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['duration_days']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-is_featured', '-is_popular', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome class e.g. fa-robot', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in sidebar/filters'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('biannual', 'Biannual (6 months)'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_best_value',
            field=models.BooleanField(default=False, help_text='Highlight as best value plan'),
        ),
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='developer',
            field=models.CharField(blank=True, help_text='Company/developer name e.g. OpenAI', max_length=200),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Visible on the site'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in Top Tools carousel on home page'),
        ),
        migrations.AddField(
            model_name='tool',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='tool',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='users_count',
            field=models.CharField(blank=True, help_text="Display string e.g. '12,000+'", max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='e.g. Monthly, Yearly, Lifetime', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='base_price_ngn',
            field=models.DecimalField(decimal_places=2, help_text='Base monthly price in NGN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image_url',
            field=models.URLField(blank=True, help_text='Tool logo/icon URL (e.g. svgl)', null=True),
        ),
    ]
