# Generated by Django 5.2.6 on 2026-07-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.tool')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ToolFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Priority access to GPT-4', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional longer description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.tool')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ToolReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=5, help_text='1 to 5 stars')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.tool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL to the screenshot image')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='products.tool')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
