# Generated by Django 5.2 on 2026-07-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_toolfaq_toolfeature_toolreview_toolscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='show_faqs_tab',
            field=models.BooleanField(default=True, help_text='Show the FAQs tab on the product page'),
        ),
        migrations.AddField(
            model_name='tool',
            name='show_features_tab',
            field=models.BooleanField(default=True, help_text='Show the Features tab on the product page'),
        ),
        migrations.AddField(
            model_name='tool',
            name='show_overview_tab',
            field=models.BooleanField(default=True, help_text='Show the Overview tab on the product page'),
        ),
        migrations.AddField(
            model_name='tool',
            name='show_reviews_tab',
            field=models.BooleanField(default=True, help_text='Show the Reviews tab on the product page'),
        ),
    ]
