# Generated by Django 5.2 on 2026-07-18 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tool_show_faqs_tab_tool_show_features_tab_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='vendor_product',
            field=models.ForeignKey(blank=True, help_text='Map this plan to a Vendor Product for auto-delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendorproduct'),
        ),
    ]
