# Generated by Django 5.2 on 2026-07-19 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_plan'),
        ('products', '0005_subscriptionplan_vendor_product'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='base_price_ngn',
        ),
        migrations.AddField(
            model_name='tool',
            name='is_manual_price',
            field=models.BooleanField(default=False, help_text='If True, it will not auto-calculate the sell price based on global markup'),
        ),
        migrations.AddField(
            model_name='tool',
            name='sell_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual override for USD sell price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='vendor_product',
            field=models.OneToOneField(blank=True, help_text='Link this tool directly to a Vendor Product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendorproduct'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
