# Generated by Django 5.2 on 2026-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_tool_base_price_ngn_tool_is_manual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='markup_fixed_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Per-tool fixed USD profit (overrides per-tool percentage and global)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tool',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Per-tool percentage profit (overrides global)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tool',
            name='is_manual_price',
            field=models.BooleanField(default=False, help_text='If True, it will not auto-calculate the sell price based on markups'),
        ),
    ]
