# Generated by Django 5.2 on 2026-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_ai_refined',
            field=models.BooleanField(default=False, help_text='Indicates whether this tool has been refined using OpenRouter AI.'),
        ),
    ]
