# Generated by Django 5.2.6 on 2026-07-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_code", models.CharField(max_length=10, unique=True)),
                ("rate_to_ngn", models.DecimalField(decimal_places=4, max_digits=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
