# Generated by Django 5.2 on 2026-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_public_key', models.CharField(blank=True, default='', help_text='Paystack public key (pk_test_... or pk_live_...)', max_length=200)),
                ('paystack_secret_key', models.CharField(blank=True, default='', help_text='Paystack secret key (sk_test_... or sk_live_...)', max_length=200)),
                ('is_live_mode', models.BooleanField(default=False, help_text='When enabled, live Paystack keys are used. Keep OFF during testing.')),
                ('transaction_fee_percent', models.DecimalField(decimal_places=2, default=1.5, help_text='% fee added to each transaction (e.g. 1.50 = 1.5%)', max_digits=5)),
                ('referral_commission_ngn', models.DecimalField(decimal_places=2, default=2000.0, help_text='Fixed NGN commission credited to referrer when their referral makes first purchase', max_digits=10)),
                ('min_withdrawal_ngn', models.DecimalField(decimal_places=2, default=5000.0, help_text='Minimum NGN balance required to submit a withdrawal request', max_digits=10)),
                ('support_email', models.EmailField(default='support@onesolai.com', max_length=254)),
                ('site_name', models.CharField(default='OneSol AI Hub', max_length=100)),
                ('site_url', models.URLField(default='https://onesolai.com', help_text='Full site URL including https (used in emails and referral links)')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
