# Generated by Django 5.2.6 on 2026-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='referral_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='% commission if "Percentage" is selected above (e.g. 10.00 = 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_commission_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Sale')], default='fixed', help_text='Type of commission paid out to the referrer.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_reward_frequency',
            field=models.CharField(choices=[('first_purchase', 'Only on First Purchase'), ('every_purchase', 'On Every Subscription Purchase')], default='every_purchase', help_text="How often should the referrer get paid for a referred user's purchases?", max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='referral_commission_ngn',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Fixed NGN commission if "Fixed Amount" is selected above.', max_digits=10),
        ),
    ]
