# Generated by Django 5.2 on 2026-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_referral_commission_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(blank=True, max_length=100)),
                ('title_line_2_start', models.CharField(blank=True, max_length=100)),
                ('title_line_2_highlight', models.CharField(blank=True, max_length=100)),
                ('title_line_2_end', models.CharField(blank=True, max_length=100)),
                ('title_line_3', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='HTML allowed (e.g. <br>)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('primary_button_text', models.CharField(blank=True, max_length=50)),
                ('primary_button_url', models.CharField(blank=True, max_length=255)),
                ('primary_button_icon', models.CharField(blank=True, help_text='e.g. fas fa-compass', max_length=50)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('show_features_block', models.BooleanField(default=False, help_text='Show the features block (Local currency, Instant delivery, etc) below description.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
    ]
