# Generated by Django 5.2 on 2026-07-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Upload the site logo to replace the default one', null=True, upload_to='site_logos/'),
        ),
    ]
