# Generated by Django 5.2 on 2026-07-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='global_markup_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='% to add to vendor USD price for profit (e.g. 20.00 = 20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usd_to_ngn_rate',
            field=models.DecimalField(decimal_places=2, default=1500.0, help_text='Exchange rate to convert USD to local currency (NGN) on the frontend', max_digits=10),
        ),
    ]
