# Generated by Django 5.2 on 2026-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_global_markup_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='global_markup_fixed_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed USD profit to add instead of percentage. If greater than 0, overrides percentage.', max_digits=10),
        ),
    ]
