# Generated by Django 5.2 on 2026-07-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_global_markup_fixed_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, help_text='Upload the site favicon (ideally 32x32 or 64x64). If not provided, site logo is used.', null=True, upload_to='site_logos/'),
        ),
    ]
