# Generated by Django 5.2 on 2026-07-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_site_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='openrouter_api_key',
            field=models.CharField(blank=True, default='', help_text='OpenRouter API Key for refining product descriptions', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='openrouter_model',
            field=models.CharField(default='meta-llama/llama-3.1-8b-instruct:free', help_text='OpenRouter Model ID (e.g., meta-llama/llama-3.1-8b-instruct:free, google/gemini-2.5-flash)', max_length=100),
        ),
    ]
