# Generated by Django 5.2 on 2026-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_openrouter_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='openrouter_model',
            field=models.CharField(default='meta-llama/llama-3-8b-instruct:free', help_text='OpenRouter Model ID (e.g., meta-llama/llama-3-8b-instruct:free, google/gemini-2.5-flash)', max_length=100),
        ),
    ]
