# Generated by Django 5.2 on 2026-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_openrouter_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='openrouter_model',
            field=models.CharField(default='openrouter/free', help_text='OpenRouter Model ID (e.g., openrouter/free, openrouter/auto, google/gemini-2.5-flash)', max_length=100),
        ),
    ]
