# Generated by Django 5.2 on 2026-07-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_newslettersubscriber_sitesettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='flutterwave_encryption_key',
            field=models.CharField(blank=True, default='', help_text='Flutterwave encryption key (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='flutterwave_public_key',
            field=models.CharField(blank=True, default='', help_text='Flutterwave public key (FLWPUBK_TEST-... or FLWPUBK_LIVE-...)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='flutterwave_secret_key',
            field=models.CharField(blank=True, default='', help_text='Flutterwave secret key (FLWSECK_TEST-... or FLWSECK_LIVE-...)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_flutterwave_enabled',
            field=models.BooleanField(default=True, help_text='Enable Flutterwave payment gateway on checkout.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_paystack_enabled',
            field=models.BooleanField(default=True, help_text='Enable Paystack payment gateway on checkout.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_payment_gateway',
            field=models.CharField(choices=[('paystack', 'Paystack (Primary)'), ('flutterwave', 'Flutterwave (Primary)')], default='paystack', help_text='Primary gateway used for payments. Platform will fallback to secondary gateway if primary fails, is disabled, or does not support user currency.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_content',
            field=models.TextField(blank=True, help_text='Custom HTML or text for Privacy Policy page. Leave blank to use default template content.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='refund_policy_content',
            field=models.TextField(blank=True, help_text='Custom HTML or text for Refund Policy page. Leave blank to use default template content.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_content',
            field=models.TextField(blank=True, help_text='Custom HTML or text for Terms of Service page. Leave blank to use default template content.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='is_live_mode',
            field=models.BooleanField(default=False, help_text='When enabled, live payment gateway keys are used. Keep OFF during testing.'),
        ),
    ]
