# Generated by Django 5.2 on 2026-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_sitesettings_privacy_policy_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_image',
            field=models.ImageField(blank=True, help_text='Custom image graphic for the About Us section on the homepage', null=True, upload_to='site/'),
        ),
    ]
