# Generated by Django 5.2 on 2026-07-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesettings_about_us_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us_image',
            field=models.ImageField(blank=True, help_text='Image to display on the right side of the About Us section on the homepage.', null=True, upload_to='site/'),
        ),
    ]
