# Generated by Django 5.2 on 2026-07-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sitesettings_about_us_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='flutterwave_encryption_key',
            field=models.CharField(blank=True, default='', help_text='Paste your Flutterwave Encryption key here (optional, used for webhook verification and encryption).', max_length=200, verbose_name='Flutterwave Encryption Key'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='flutterwave_public_key',
            field=models.CharField(blank=True, default='', help_text='Paste your Flutterwave Public Key (FLWPUBK_...) OR V4 Client ID here.', max_length=200, verbose_name='Flutterwave Public Key / Client ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='flutterwave_secret_key',
            field=models.CharField(blank=True, default='', help_text='Paste your Flutterwave Secret Key (FLWSECK_...) OR V4 Client Secret here.', max_length=200, verbose_name='Flutterwave Secret Key / Client Secret'),
        ),
    ]
