# Generated by Django 5.2 on 2026-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_sitesettings_flutterwave_encryption_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='flutterwave_api_version',
            field=models.CharField(choices=[('v3', 'V3 API Keys (Standard)'), ('v4', 'V4 API Keys (OAuth 2.0)')], default='v3', help_text='Select the API version for the keys pasted below.', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='flutterwave_encryption_key',
            field=models.CharField(blank=True, default='', help_text='Paste your Flutterwave Encryption key here (optional).', max_length=200, verbose_name='Flutterwave Encryption Key'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='flutterwave_public_key',
            field=models.CharField(blank=True, default='', help_text='For V3: Paste your Public Key (FLWPUBK_...). For V4: Paste your Client ID.', max_length=200, verbose_name='Flutterwave Public Key / Client ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='flutterwave_secret_key',
            field=models.CharField(blank=True, default='', help_text='For V3: Paste your Secret Key (FLWSECK_...). For V4: Paste your Client Secret.', max_length=200, verbose_name='Flutterwave Secret Key / Client Secret'),
        ),
    ]
