# Generated by Django 5.2 on 2026-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings_flutterwave_api_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='is_live_mode',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='flutterwave_is_live_mode',
            field=models.BooleanField(default=False, help_text='Check if using Flutterwave Live keys. Uncheck for Test keys.', verbose_name='Flutterwave Live Mode'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paystack_is_live_mode',
            field=models.BooleanField(default=False, help_text='Check if using Paystack Live keys. Uncheck for Test keys.', verbose_name='Paystack Live Mode'),
        ),
    ]
