# Generated by Django 5.2 on 2026-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_faq_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='trust_bar_left_text',
            field=models.CharField(default='Trusted by <strong>1,000+</strong> users across Africa', help_text='Left text in trust bar (HTML allowed, e.g. <strong>1,000+</strong>)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_bar_rating_score',
            field=models.CharField(default='4.9/5', help_text='Rating score display in trust bar (e.g. 4.9/5)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_bar_right_text',
            field=models.CharField(default='from <strong>500+</strong> reviews', help_text='Right text in trust bar (HTML allowed, e.g. <strong>500+</strong>)', max_length=255),
        ),
    ]
