# Generated by Django 5.2 on 2026-07-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitesettings_trust_bar_left_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_client_id',
            field=models.CharField(blank=True, default='', help_text='Google Client ID from Google Cloud Console (e.g., xxx.apps.googleusercontent.com)', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_client_secret',
            field=models.CharField(blank=True, default='', help_text='Google Client Secret from Google Cloud Console', max_length=300),
        ),
    ]
