# Generated by Django 5.2 on 2026-07-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sitesettings_google_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='crypto_instructions',
            field=models.TextField(blank=True, default='Send the exact amount in USDT to the wallet address below, then copy and paste your Transaction Hash (TxID) to verify your payment.', help_text='Instructions displayed to users paying with crypto.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='crypto_usdt_address',
            field=models.CharField(blank=True, default='', help_text='Platform USDT wallet address for receiving crypto checkout payments.', max_length=200, verbose_name='Crypto USDT Receiving Wallet Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='crypto_usdt_network',
            field=models.CharField(default='USDT (TRC20)', help_text='Network e.g. USDT (TRC20) or USDT (BEP20).', max_length=50, verbose_name='Crypto USDT Network'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_crypto_enabled',
            field=models.BooleanField(default=True, help_text='Enable Crypto (USDT) payment gateway on checkout.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_payment_gateway',
            field=models.CharField(choices=[('paystack', 'Paystack (Primary)'), ('flutterwave', 'Flutterwave (Primary)'), ('crypto', 'Crypto USDT (Primary)')], default='paystack', help_text='Primary gateway used for payments. Platform will fallback to secondary gateway if primary fails, is disabled, or does not support user currency.', max_length=20),
        ),
    ]
