# Generated by Django 5.2 on 2026-07-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sitesettings_crypto_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_image',
            field=models.ImageField(blank=True, help_text='Custom hero image for the Contact Us page. If left empty, default image is used.', null=True, upload_to='site/', verbose_name='Contact Us Hero Image'),
        ),
    ]
