# Generated by Django 5.2 on 2026-07-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sitesettings_contact_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='referral_page_content',
            field=models.TextField(blank=True, default='<h2><i class="fas fa-gift"></i> 1. Overview & Commission Structure</h2>\n<p>Welcome to the <strong>OneSol AI Hub Refer & Earn Program</strong>! Share your unique referral link with friends, creators, colleagues, or social media followers and earn generous cash commissions for every successful order placed.</p>\n\n<div class="legal-highlight-box">\n    <strong>Generous Payouts:</strong> Earn cash rewards credited directly to your OneSol Wallet balance. Withdraw anytime straight to your bank account or crypto wallet once you reach the minimum threshold.\n</div>\n\n<h2><i class="fas fa-route"></i> 2. How It Works (Step-by-Step)</h2>\n<ul>\n    <li><strong>Get Your Link:</strong> Sign in to your OneSol AI Hub account and copy your unique referral link from your User Dashboard or this page.</li>\n    <li><strong>Share & Promote:</strong> Share your link via WhatsApp, Telegram, Twitter, YouTube, blog posts, or direct messages.</li>\n    <li><strong>Earn Cash:</strong> When someone clicks your link and purchases any AI tool subscription, your earnings wallet is automatically credited!</li>\n</ul>\n\n<h2><i class="fas fa-wallet"></i> 3. Withdrawal Rules & Guidelines</h2>\n<p>Withdrawals are fast, transparent, and hassle-free:</p>\n<ul>\n    <li><strong>Minimum Withdrawal:</strong> You can request a payout as soon as your balance reaches <strong>NGN 5,000</strong> (or crypto equivalent).</li>\n    <li><strong>Supported Payout Methods:</strong> Local Bank Account Transfer or Crypto (USDT TRC20/BEP20).</li>\n    <li><strong>Anti-Fraud Policy:</strong> Self-referrals, spamming, or creating fake accounts to manipulate referral links are strictly monitored and forbidden.</li>\n</ul>\n\n<h2><i class="fas fa-headset"></i> 4. Need Help or Have Questions?</h2>\n<p>If you have questions about custom affiliate partnerships, bulk reseller rates, or referral tracking, contact our team at <strong>info@onesolai.com</strong>.</p>\n<div class="updated-date">Last Updated: July 2026 | OneSol AI Hub Referral Team</div>', help_text='Custom HTML or text for Refer & Earn page. Edit or replace this text anytime.'),
        ),
    ]
