# Generated by Django 5.2 on 2026-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sitesettings_referral_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(default='General Inquiry', max_length=50)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved / Responded')),
                ('admin_note', models.TextField(blank=True, help_text='Internal notes for support staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
