# Generated by Django 5.2 on 2026-08-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='markup_type',
            field=models.CharField(choices=[('percent', 'Global Percentage Markup (%)'), ('fixed', 'Global Fixed USD Amount ($)')], default='percent', help_text='Select whether to calculate product profit markup using a Percentage (%) or a Fixed USD ($) amount.', max_length=20, verbose_name='Active Markup Strategy'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='global_markup_fixed_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed USD profit to add to vendor USD price when Fixed USD Amount is selected above (e.g. 5.00 = $5 profit).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='global_markup_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='% to add to vendor USD price for profit when Percentage Markup is selected above (e.g. 20.00 = 20%)', max_digits=5),
        ),
    ]
