# Generated by Django 5.2 on 2026-08-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sitesettings_markup_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='livechat_enabled',
            field=models.BooleanField(default=True, help_text='Toggle to show or hide the live chat widget across the entire site.', verbose_name='Enable Live Chat Widget'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='livechat_script',
            field=models.TextField(blank=True, default='<script\n  src="https://hglobal.store/widget.js"\n  data-widget-id="1"\n  data-agent-id="5"\n  data-title="Onesolai"\n  data-bg-color="%235e0303"\n  data-position="left"\n  data-show-support="true"\n  data-support-email="support@tripowercircle.com.ng"\n></script>', help_text="Paste the full live chat widget &lt;script&gt; tag here. Clear this field entirely to remove the widget. Use the 'Enable Live Chat Widget' toggle above to temporarily hide/show it without deleting the script.", verbose_name='Live Chat Widget Script'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='livechat_show_on_dashboard',
            field=models.BooleanField(default=True, help_text='If unchecked, the widget will only appear on public pages (not inside the user dashboard).', verbose_name='Show on Dashboard Pages'),
        ),
    ]
