"""
Django settings for onesolai project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-acfd7!cbf901$vggt81l17o%(#7pd5^txexbbu1q!siy*c(zy_"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app']

# Allow CSRF POST requests from any ngrok subdomain
CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "core",
    "products",
    "orders",
    "notifications",
    "vendors",
    "analytics",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "onesolai.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.unread_notifications",
                "core.context_processors.site_settings",
                "core.context_processors.currency_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "onesolai.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CELERY SETTINGS
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE


# ─────────────────────────────────────────────
# Authentication
# ─────────────────────────────────────────────
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# ─────────────────────────────────────────────
# Email (console backend for development)
# ─────────────────────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'OneSol AI Hub <noreply@onesolai.com>'

# ─────────────────────────────────────────────
# Payment Gateways
# ─────────────────────────────────────────────
# Paystack
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', 'pk_test_xxxx')
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', 'sk_test_xxxx')
PAYSTACK_CALLBACK_URL = os.environ.get('PAYSTACK_CALLBACK_URL', 'http://127.0.0.1:8000/payments/paystack/callback/')

# Flutterwave
FLUTTERWAVE_PUBLIC_KEY = os.environ.get('FLW_PUBLIC_KEY', 'FLWPUBK_TEST-xxxx')
FLUTTERWAVE_SECRET_KEY = os.environ.get('FLW_SECRET_KEY', 'FLWSECK_TEST-xxxx')
FLUTTERWAVE_ENCRYPTION_KEY = os.environ.get('FLW_ENCRYPTION_KEY', '')
FLUTTERWAVE_CALLBACK_URL = os.environ.get('FLW_CALLBACK_URL', 'http://127.0.0.1:8000/payments/flutterwave/callback/')

# ─────────────────────────────────────────────
# Currency
# ─────────────────────────────────────────────
# Base currency for all products
BASE_CURRENCY = 'NGN'

# Supported African currencies and their approximate rates to NGN
# These are fallback rates; the app fetches live rates where possible
CURRENCY_RATES_FALLBACK = {
    'NGN': 1,
    'GHS': 0.044,    # Ghanaian Cedi
    'KES': 0.12,     # Kenyan Shilling
    'ZAR': 0.021,    # South African Rand
    'UGX': 43.5,     # Ugandan Shilling
    'TZS': 29.8,     # Tanzanian Shilling
    'RWF': 15.4,     # Rwandan Franc
    'XOF': 6.5,      # West African CFA Franc
    'XAF': 6.5,      # Central African CFA Franc
    'ZMW': 0.26,     # Zambian Kwacha
    'MWK': 19.8,     # Malawian Kwacha
    'MUR': 0.52,     # Mauritian Rupee
    'EGP': 0.35,     # Egyptian Pound
    'ETB': 13.2,     # Ethiopian Birr
    'USD': 0.00063,  # US Dollar
    'GBP': 0.00050,  # British Pound
    'EUR': 0.00058,  # Euro
}

CURRENCY_SYMBOLS = {
    'NGN': '₦', 'GHS': 'GH₵', 'KES': 'KSh', 'ZAR': 'R',
    'UGX': 'USh', 'TZS': 'TSh', 'RWF': 'FRw', 'XOF': 'CFA',
    'XAF': 'CFA', 'ZMW': 'K', 'MWK': 'MK', 'MUR': '₨',
    'EGP': 'E£', 'ETB': 'Br', 'USD': '$', 'GBP': '£', 'EUR': '€',
}

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "OneSol AI Hub Admin",
    
    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "OneSol AI Hub",
    
    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "",
    
    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "assets/logo.png",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to OneSol AI Hub Administration",
    
    # Copyright on the footer
    "copyright": "OneSol AI Hub Ltd",
    
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
    
    # Custom CSS for the admin
    "custom_css": "css/admin_jazzmin_custom.css",
    
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Frontend", "url": "home", "new_window": False},
        {"name": "Admin Analytics", "url": "analytics:dashboard", "new_window": False},
    ],
    
    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts.User": "fas fa-user-shield",
        "accounts.Profile": "fas fa-id-badge",
        "products.Category": "fas fa-tags",
        "products.Tool": "fas fa-layer-group",
        "vendors.Vendor": "fas fa-plug",
        "vendors.VendorBalance": "fas fa-wallet",
        "orders.Order": "fas fa-cart-shopping",
        "orders.PaymentTransaction": "fas fa-money-bill-transfer",
        "orders.OrderAPIRequest": "fas fa-server",
        "core.SiteSettings": "fas fa-gear",
    },
    
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "navbar": "navbar-dark",
    "navbar_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
